name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install shellcheck & shfmt
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          curl -sSLo /usr/local/bin/shfmt https://github.com/mvdan/sh/releases/download/v3.7.0/shfmt_v3.7.0_linux_amd64
          chmod +x /usr/local/bin/shfmt

      - name: Shellcheck
        run: shellcheck scripts/post_install.sh

      - name: shfmt (check only)
        run: shfmt -d -i 2 -ci -sr scripts/post_install.sh
